### PR TITLE
feat(public/migrate): more error handling

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Comment by clintre** [comment]
Tested Fedora KDE 41
Result: Passed

Tested Fedora Budgie 41
Result Failed
`Problem: installed package budgie-desktop-defaults-0.5.1-5.fc41.noarch conflicts with budgie-desktop-defaults provided by ultramarine-flagship-filesystem-41-6.2.um41.x86_64 from ultramarine
  
cannot install the best candidate for the job
You can try to add to command line:
  --no-best to not limit the transaction to the best candidates
  --skip-broken to skip uninstallable packages`

**Comment by clintre** [comment]
Testing Fedora XFCE 41 Migration
Result: Failed

`Problem: installed package desktop-backgrounds-compat-41.0.0-1.fc41.noarch conflicts with desktop-backgrounds-compat provided by ultramarine-backgrounds-compat-41.2-1.um41.noarch from ultramarine
  - cannot install the best candidate for the job
  - conflicting requests
You can try to add to command line:
  --no-best to not limit the transaction to the best candidates
  --skip-broken to skip uninstallable packages`

**Comment by clintre** [comment]
Tested Fedora Gnome 41
Result: Passed

**Comment by clintre** [comment]
Testing Migration on Fedora 41 with pre-installed Terra.
Result: Failed

`...[2/3] Terra
+ sudo dnf install -y --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' --setopt=terra.gpgkey=https://repos.fyralabs.com/terra41/key.asc terra-release
Failed to create repo "terra": Id is present more than once in the configuration`

**Comment by clintre** [comment]
Re-Tested with pre-installed terra repo multiple times. This time it ran as expected each time. So it may have been a false positive on the other test.

Budgie and XFCE problems were both re-produced.

**Comment by madonuko** [comment]
related: https://github.com/Ultramarine-Linux/packages/pull/104

**Comment by clintre** [comment]
Retest XFCE was a success.

Retest of Budgie failed again. Attaching log, but it is a conflict still...
```
installed package budgie-desktop-defaults-0.5.1-5.fc41.noarch conflicts with budgie-desktop-defaults provided by ultramarine-flagship-filesystem-41-6.2.um41.x86_64 from ultramarine
  - cannot install the best candidate for the job
```
[budgie41-test-ultramarine-migrate.log](https://github.com/user-attachments/files/18115065/budgie41-test-ultramarine-migrate.log)

**Comment by clintre** [comment]
Retest of Budgie and now it works perfectly!

**Review by nothingneko — COMMENTED** [review]
tested yes yes?

**Comment by madonuko** [comment]
> tested yes yes?

pass in virtualbox (big thanks to clintre!) and podman, 4 editions + no edition

**Pull request merged**
