### PR TITLE
fix[#13] Darkmode and Light mode

### PR DESCRIPTION
**Pull request by muhdsalm**

### CODE REVIEW

**Review by lleyton — CHANGES_REQUESTED** [review]
Thank you! A couple of suggestions:
- Where are these icons from?
- Could you put the theme switch button into its own Vue component?

**Comment by muhdsalm** [comment]
The icons are from Bootstrap icons, but I've hardcoded the SVG values so it should work even if Bootstrap icons happens to be offline.

**Comment by muhdsalm** [comment]
> Thank you! A couple of suggestions:
> 
> * Where are these icons from?
> * Could you put the theme switch button into its own Vue component?

Is an Astro component okay?

**Comment by lleyton** [comment]
While I don't particularly mind it, doing it as Vue component would probably be better as that's what most of the site uses for interactive elements IIRC

**Comment by muhdsalm** [comment]
Done. My first experience with SSR. Definitely enjoyed it (not really) :P

**Pull request merged**
