### PR TITLE
Pride logo for this month

### PR DESCRIPTION
**Pull request by nothingneko**

### CODE REVIEW

**Comment by lleyton** [comment]
The logo is inlined https://github.com/Ultramarine-Linux/website/blob/8e658b3e7a55b93f0bfe6d84e2b220fab370f75f/src/components/Header.astro#L15

**Comment by nothingneko** [comment]
> The logo is inlined
> 
> https://github.com/Ultramarine-Linux/website/blob/8e658b3e7a55b93f0bfe6d84e2b220fab370f75f/src/components/Header.astro#L15

i didn't touch that file

**Comment by lleyton** [comment]
yes, but the logo doesn't show up in the header bar because it's currently inlined

**Comment by nothingneko** [comment]
I don't know what to do here

**Comment by lleyton** [comment]
I think you could use an astro image component here

**Comment by nothingneko** [comment]
1. I don't know what that means
2. I don't know how to do that
3. Why does this logo break it they are the same size and format
4. If this is generally broken then why is it on me to fix

**Comment by lleyton** [comment]
1. The logo in the header is currently inlined, the literal SVG code is in-line in that file, You didn’t update the inlined logo, so the original one shows in the header.
2. There are many places where images are used in the codebase, you can refer to those. Also see https://docs.astro.build/en/guides/images/
3. See 1
4. You are trying to ship a feature, I review the PR, the feature doesn’t work, if you encounter a “bug” that prevents you from implementing the feature, you need to solve the problem to get it shipped.

When you ran the development server on your machine, did it work?

**Comment by nothingneko** [comment]
I didn’t test because I assumed it would be a drop in replacement as one would assume images would be

**Comment by nothingneko** [comment]
I will figure out inlining it ig

**Comment by lleyton** [comment]
> I didn’t test because I assumed it would be a drop in replacement as one would assume images would be

You should still test your changes, also did you check where that image was referenced in the project?

**Comment by nothingneko** [comment]
no because I assumed that the ultramarine-logo file in assets was the one we used to provide the logo (as a reasonable person would)

**Review by lleyton — APPROVED** [review]

**Pull request merged**
